In [23]:
import numpy as np                
from matplotlib import colors     
from sklearn import svm            
from sklearn.svm import SVC
from sklearn import model_selection
import matplotlib.pyplot as plt
import matplotlib as mpl

import pandas as pd

# 利用pandas库加载数据

In [24]:
data=pd.read_csv("/Users/juanitahowe/Documents/GitHub/BNU_intro_AI/(2023_10_12)作业五_机器学习/wine.csv")
data=data.to_numpy()

* 划分数据特征和结果
* 划分训练集和测试集

In [25]:
x, y = np.split(data,                                       #要切分的数组
                (13,),                                       #沿轴切分的位置，第5列开始往后为y
                axis=1)                                     #代表纵向分割，按列分割                                          
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,              #所要划分的样本特征集
                                                               y,              #所要划分的样本结果
                                                               random_state=1, #随机数种子
                                                               test_size=0.3)  #测试样本占比

# 构建分类器

In [26]:
#**********************SVM分类器构建*************************
def classifier():
    #clf = svm.SVC(C=0.8,kernel='rbf', gamma=50,decision_function_shape='ovr')
    clf = svm.SVC(C=0.5,                         #误差项惩罚系数,默认值是1
                  kernel='linear',               #线性核 kenrel="rbf":高斯核
                  decision_function_shape='ovr') #决策函数
    return clf
# 2.定义模型：SVM模型定义
clf = classifier()

# 训练模型

In [27]:
#***********************训练模型*****************************
def train(clf,x_train,y_train):
    clf.fit(x_train,         #训练集特征向量
            y_train.ravel()) #训练集目标值
# 3.训练SVM模型
train(clf,x_train,y_train)

# 模型评估

In [28]:
#**************并判断a b是否相等，计算acc的均值*************
def show_accuracy(a, b, tip):
    acc = a.ravel() == b.ravel()
    print('%s Accuracy:%.3f' %(tip, np.mean(acc)))

In [29]:
def print_accuracy(clf,x_train,y_train,x_test,y_test):
    #分别打印训练集和测试集的准确率  score(x_train,y_train):表示输出x_train,y_train在模型上的准确率
    print('trianing prediction:%.3f' %(clf.score(x_train, y_train)))
    print('test data prediction:%.3f' %(clf.score(x_test, y_test)))
    #原始结果与预测结果进行对比   predict()表示对x_train样本进行预测，返回样本类别
    show_accuracy(clf.predict(x_train), y_train, 'traing data')
    show_accuracy(clf.predict(x_test), y_test, 'testing data')
    #计算决策函数的值，表示x到各分割平面的距离
    print('decision_function:\n', clf.decision_function(x_train))

In [30]:
# 4.模型评估
print_accuracy(clf,x_train,y_train,x_test,y_test)

trianing prediction:0.984
test data prediction:0.963
traing data Accuracy:0.984
testing data Accuracy:0.963
decision_function:
 [[-0.28085401  2.29356059  0.77670523]
 [ 1.21163674  2.27146598 -0.28656234]
 [ 2.26730056  0.82189689 -0.2478775 ]
 [ 0.76628569  2.28920287 -0.26932038]
 [-0.2231656   0.76604201  2.27137518]
 [ 0.7822573   2.2787738  -0.2544527 ]
 [ 0.83334723  2.2602991  -0.23981167]
 [ 2.28747812 -0.27894288  0.82237667]
 [ 0.80026018 -0.28636511  2.29453813]
 [-0.27122419  2.2901333   0.76619452]
 [-0.26854153  1.15889174  2.25460231]
 [ 2.29449368  0.73608887 -0.26360935]
 [-0.26445023  2.28577058  0.77184671]
 [ 2.2941177  -0.28984979  0.84839134]
 [ 0.72512681  2.29976908 -0.26959005]
 [ 2.24740591  0.91935499 -0.23970286]
 [-0.26475691  0.73438304  2.29538231]
 [ 1.13542782 -0.29875597  2.29611397]
 [ 0.92919644 -0.28479054  2.28662503]
 [ 1.23552203 -0.30250052  2.2936653 ]
 [-0.27257688  2.27263592  0.99823074]
 [-0.28061893  2.29056975  0.8015423 ]
 [ 2.2420942  